spring:
  config:
    activate:
      on-profile: prod

  # Prod PostgreSQL (JPA) Settings
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false

  # Prod MongoDB Settings
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: monew

      uuid-representation: standard


logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.hibernate.SQL: INFO